[package]
name = "rsysy"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
koopa = "0.0.7"
lalrpop-util = {version = "0.20.0", features = ["lexer"]}
colored = "2"
clap = { version = "4.3.1", features = ["derive"] }

[build-dependencies]
lalrpop = "0.20.0"
